main: main.cpp iargument.h flagargument.h valueargument.h argparser.h
	g++ main.cpp -o main -std=c++17

debug: main.cpp iargument.h flagargument.h valueargument.h argparser.h
	g++ -g main.cpp -o main_debug -std=c++17