main0: main0.cpp leaf_node.cpp node.cpp abstract_node.cpp
	g++ main0.cpp leaf_node.cpp node.cpp abstract_node.cpp -o main -std=c++11

main3: main3.cpp leaf_node.cpp node.cpp abstract_node.cpp
	g++ main3.cpp leaf_node.cpp node.cpp abstract_node.cpp -o main -std=c++11

main6: main6.cpp leaf_node.cpp node.cpp abstract_node.cpp
	g++ main6.cpp leaf_node.cpp node.cpp abstract_node.cpp -o main -std=c++11

main8: main8.cpp leaf_node.cpp node.cpp abstract_node.cpp
	g++ main8.cpp leaf_node.cpp node.cpp abstract_node.cpp -o main -std=c++11